-- The scoring rubric. Seeded rather than migrated in, so guidelines can be
-- edited, deactivated or added without touching schema.
--
-- Weights: 3 = a real problem, 2 = worth fixing, 1 = polish.
insert into resume_guidelines (category, guideline, weight) values
  ('impact', 'Every bullet leads with an accomplishment, not a job duty', 3),
  ('impact', 'Bullets quantify results with numbers, percentages, scale or time saved', 3),
  ('impact', 'Metrics name the baseline, so a percentage means something', 2),
  ('impact', 'Outcomes are stated, not just the activity that produced them', 3),
  ('impact', 'The candidate''s own contribution is distinguishable from the team''s', 2),
  ('impact', 'No bullet ends at ''responsible for'' without saying what came of it', 2),
  ('impact', 'Scale is given where it matters — users, requests, data volume, dollars', 2),
  ('impact', 'Achievements are specific to this candidate, not generic to the role', 2),
  ('relevance', 'Skills named in the job description appear in the resume where truthful', 3),
  ('relevance', 'The most relevant experience appears earliest in its section', 3),
  ('relevance', 'Bullets closest to the job''s core responsibilities lead each role', 2),
  ('relevance', 'Technologies listed in the job posting are visible in project or work bullets', 3),
  ('relevance', 'Domain vocabulary from the posting is mirrored where it applies honestly', 2),
  ('relevance', 'Irrelevant coursework and hobbies do not crowd out relevant work', 2),
  ('relevance', 'Seniority of the language matches the seniority of the role applied for', 1),
  ('relevance', 'Projects chosen for display are the ones closest to this job', 2),
  ('keywords', 'Exact keyword forms from the posting appear, not only synonyms', 3),
  ('keywords', 'Both the acronym and the expansion appear at least once (e.g. CI/CD)', 2),
  ('keywords', 'Hard requirements from the posting are addressed somewhere in the resume', 3),
  ('keywords', 'Keywords appear inside real bullets, not only in a skills list', 2),
  ('keywords', 'No keyword stuffing — every term is backed by actual experience', 3),
  ('keywords', 'Job title language is close enough to the posting to survive a keyword filter', 2),
  ('language', 'Bullets start with a strong past-tense verb', 2),
  ('language', 'No repeated opening verb across consecutive bullets', 1),
  ('language', 'Weak verbs are avoided: helped, worked on, assisted, participated', 2),
  ('language', 'No first-person pronouns', 1),
  ('language', 'Present tense only for the current role, past tense everywhere else', 1),
  ('language', 'No filler adverbs: successfully, effectively, various, several', 1),
  ('language', 'Sentences are direct — no clauses that add words without meaning', 1),
  ('language', 'Buzzwords without evidence are absent: synergy, rockstar, ninja, guru', 1),
  ('language', 'Technical terms are spelled the way the industry spells them', 1),
  ('language', 'Voice is active, not passive', 2),
  ('structure', 'Contact details are complete: name, email, phone, LinkedIn, GitHub', 3),
  ('structure', 'Sections are ordered by relevance to the target role', 2),
  ('structure', 'Experience is reverse-chronological within each section', 2),
  ('structure', 'Each role has company, title, location and dates', 3),
  ('structure', 'Dates use a consistent format throughout', 1),
  ('structure', 'No unexplained employment gaps longer than six months', 1),
  ('structure', 'Education placement matches career stage — top for students, lower for experienced', 1),
  ('structure', 'A skills section exists and is grouped by category', 2),
  ('structure', 'Bullets per role are between two and six', 1),
  ('structure', 'One page for under ten years of experience', 2),
  ('formatting', 'A single font family throughout', 1),
  ('formatting', 'Consistent bullet character and indentation', 1),
  ('formatting', 'Consistent spacing between sections', 1),
  ('formatting', 'Margins are between 0.5 and 1 inch', 1),
  ('formatting', 'Body text is between 10 and 12 point', 1),
  ('formatting', 'No tables, text boxes, columns or images that break resume parsers', 3),
  ('formatting', 'No headers or footers holding information a parser needs', 2),
  ('formatting', 'Section headings are visually distinct and consistent', 1),
  ('formatting', 'Bullets fit on one or two lines each', 1),
  ('formatting', 'The document has no orphaned single-word lines', 1),
  ('evidence', 'Every claimed skill appears in at least one bullet or project', 3),
  ('evidence', 'Project bullets say what was built, with what, and to what end', 2),
  ('evidence', 'Links to code or live work are present where they exist', 2),
  ('evidence', 'Certifications include the issuing body and year', 1),
  ('evidence', 'Claims are verifiable — no unsupported superlatives', 2),
  ('evidence', 'Open-source or community contributions are named specifically', 1),
  ('correctness', 'No spelling errors', 3),
  ('correctness', 'No grammatical errors', 3),
  ('correctness', 'Punctuation is consistent — bullets all end with a period, or none do', 1),
  ('correctness', 'Capitalization of technologies is correct: JavaScript, PostgreSQL, GitHub', 2),
  ('correctness', 'Company and product names are spelled as the companies spell them', 2),
  ('correctness', 'No placeholder text left behind from a template', 3),
  ('correctness', 'Contact links resolve and are not broken', 2),
  ('correctness', 'Dates are internally consistent and do not overlap incorrectly', 2),
  ('tailoring', 'The resume reads as written for this job, not sent to everyone', 3),
  ('tailoring', 'The opening summary, if present, names the target role', 2),
  ('tailoring', 'Experience bullets are reordered per application, not fixed', 2),
  ('tailoring', 'Content the posting has no use for is trimmed', 2),
  ('tailoring', 'The company''s own language appears where it fits honestly', 1),
  ('tailoring', 'Nothing in the resume contradicts the posting''s stated requirements', 2),
  ('ats', 'The file is a text-based PDF, not a scan or image', 3),
  ('ats', 'Standard section headings are used: Experience, Education, Skills', 2),
  ('ats', 'Special characters that break parsers are avoided', 2),
  ('ats', 'No critical information lives only in a graphic or icon', 2),
  ('ats', 'The filename is professional and identifies the candidate', 1),
  ('ats', 'Contact information sits in the document body, not a header', 2)
on conflict (guideline) do nothing;
